---
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASS: changeme
      DEBUG: 1
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme

volumes:
  dev-db-data:
